
collections:
  authors:
    output: true
  news:
    output: true
  localshareda10798f8b9bb16bd2baddba911c5c7:
    output: true
  case2:
    output: true
  shorturl:
    output: true
  s:
    output: true


    
    
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "case2"
    values:
      layout: "case2"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "localshareda10798f8b9bb16bd2baddba911c5c7"
    values:
      layout: "localshare"
  - scope:
      path: ""
      type: "shorturl"
    values:
      layout: "shorturl"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "s/*"
      type: "s"
    values:
      layout: "shorturl"
