
collections:
  authors:
    output: true
  news:
    output: true
  addba911c5c7:
    output: true
  case2:
    output: true
  shorturl:
    output: true
  s:
    output: true


    
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "case2"
    values:
      layout: "case2"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "addba911c5c7"
    values:
      layout: "localshare"
